/*
    ChibiOS - Copyright (C) 2006..2015 Giovanni Di Sirio

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#include "hal.h"

#if HAL_USE_PAL || defined(__DOXYGEN__)
/**
 * @brief   PAL setup.
 * @details Digital I/O ports static configuration as defined in @p board.h.
 *          This variable is used by the HAL when initializing the PAL driver.
 */
const PALConfig pal_default_config = {
#if STM32_HAS_GPIOA
  {VAL_GPIOA_MODER, VAL_GPIOA_OTYPER, VAL_GPIOA_OSPEEDR, VAL_GPIOA_PUPDR,
   VAL_GPIOA_ODR,   VAL_GPIOA_AFRL,   VAL_GPIOA_AFRH},
#endif
#if STM32_HAS_GPIOB
  {VAL_GPIOB_MODER, VAL_GPIOB_OTYPER, VAL_GPIOB_OSPEEDR, VAL_GPIOB_PUPDR,
   VAL_GPIOB_ODR,   VAL_GPIOB_AFRL,   VAL_GPIOB_AFRH},
#endif
#if STM32_HAS_GPIOC
  {VAL_GPIOC_MODER, VAL_GPIOC_OTYPER, VAL_GPIOC_OSPEEDR, VAL_GPIOC_PUPDR,
   VAL_GPIOC_ODR,   VAL_GPIOC_AFRL,   VAL_GPIOC_AFRH},
#endif
#if STM32_HAS_GPIOD
  {VAL_GPIOD_MODER, VAL_GPIOD_OTYPER, VAL_GPIOD_OSPEEDR, VAL_GPIOD_PUPDR,
   VAL_GPIOD_ODR,   VAL_GPIOD_AFRL,   VAL_GPIOD_AFRH},
#endif
#if STM32_HAS_GPIOE
  {VAL_GPIOE_MODER, VAL_GPIOE_OTYPER, VAL_GPIOE_OSPEEDR, VAL_GPIOE_PUPDR,
   VAL_GPIOE_ODR,   VAL_GPIOE_AFRL,   VAL_GPIOE_AFRH},
#endif
#if STM32_HAS_GPIOF
  {VAL_GPIOF_MODER, VAL_GPIOF_OTYPER, VAL_GPIOF_OSPEEDR, VAL_GPIOF_PUPDR,
   VAL_GPIOF_ODR,   VAL_GPIOF_AFRL,   VAL_GPIOF_AFRH},
#endif
#if STM32_HAS_GPIOG
  {VAL_GPIOG_MODER, VAL_GPIOG_OTYPER, VAL_GPIOG_OSPEEDR, VAL_GPIOG_PUPDR,
   VAL_GPIOG_ODR,   VAL_GPIOG_AFRL,   VAL_GPIOG_AFRH},
#endif
#if STM32_HAS_GPIOH
  {VAL_GPIOH_MODER, VAL_GPIOH_OTYPER, VAL_GPIOH_OSPEEDR, VAL_GPIOH_PUPDR,
   VAL_GPIOH_ODR,   VAL_GPIOH_AFRL,   VAL_GPIOH_AFRH},
#endif
#if STM32_HAS_GPIOI
  {VAL_GPIOI_MODER, VAL_GPIOI_OTYPER, VAL_GPIOI_OSPEEDR, VAL_GPIOI_PUPDR,
   VAL_GPIOI_ODR,   VAL_GPIOI_AFRL,   VAL_GPIOI_AFRH}
#endif
};
#endif

/**
 * @brief   Early initialization code.
 * @details This initialization must be performed just after stack setup
 *          and before any other initialization.
 */
void __early_init(void) {

  stm32_clock_init();
}

#if HAL_USE_SDC || defined(__DOXYGEN__)
/**
 * @brief   SDC card detection.
 */
bool sdc_lld_is_card_inserted(SDCDriver *sdcp) {

  (void)sdcp;
  /* TODO: Fill the implementation.*/
  return true;
}

/**
 * @brief   SDC card write protection detection.
 */
bool sdc_lld_is_write_protected(SDCDriver *sdcp) {

  (void)sdcp;
  /* TODO: Fill the implementation.*/
  return false;
}
#endif /* HAL_USE_SDC */

#if HAL_USE_MMC_SPI || defined(__DOXYGEN__)
/**
 * @brief   MMC_SPI card detection.
 */
bool mmc_lld_is_card_inserted(MMCDriver *mmcp) {

  (void)mmcp;
  /* TODO: Fill the implementation.*/
  return true;
}

/**
 * @brief   MMC_SPI card write protection detection.
 */
bool mmc_lld_is_write_protected(MMCDriver *mmcp) {

  (void)mmcp;
  /* TODO: Fill the implementation.*/
  return false;
}
#endif

#if HAL_USE_SERIAL || HAL_USE_UART
SerialConfig serialConfig = {
	9600,
	0,
	0,
	0
};
#endif

#if HAL_USE_UART || HAL_USE_UART
UARTConfig uartConfig = {
    telemetryTransmitCallback,
    NULL,
    NULL,
    telemetryCharReceiveCallback,
    NULL,
    BOARD_USART2_BAUD,0,0,0
};
#endif

PWMConfig pwmConfig = {
	1000000,
	20000,
	NULL,
	{
	{PWM_OUTPUT_ACTIVE_HIGH, NULL},
	{PWM_OUTPUT_ACTIVE_HIGH, NULL},
	{PWM_OUTPUT_ACTIVE_HIGH, NULL},
	{PWM_OUTPUT_ACTIVE_HIGH, NULL},
	},
	0,
	0
};

SPIConfig spi1Config = {
	NULL,
	NULL,
	0,
    SPI_CR1_DFF | SPI_CR1_CPOL | SPI_CR1_CPHA | SPI_CR1_BR_2 | SPI_CR1_BR_1 | SPI_CR1_BR_0
};

SPIConfig spi2Config = {
	NULL,
	NULL,
	0,
	//SPI_CR1_BR_2// | SPI_CR1_BR_1// | SPI_CR1_BR_0
	SPI_CR1_CPHA | SPI_CR1_BR_1
};

/**
 * @brief   Board-specific initialization code.
 */
void boardInit(void) {
	// peripheral inint
    #if STM32_SERIAL_USE_USART1
	palSetPadMode(BOARD_USART1_TX_PORT, BOARD_USART1_TX_PIN, PAL_MODE_ALTERNATE(7));
	palSetPadMode(BOARD_USART1_RX_PORT, BOARD_USART1_RX_PIN, PAL_MODE_ALTERNATE(7));

    serialConfig.speed = BOARD_USART1_BAUD;
    sdStart(&SD1, &serialConfig);
	#endif


    #if STM32_SERIAL_USE_USART2
	palSetPadMode(BOARD_USART2_CTS_PORT, BOARD_USART2_CTS_PIN, PAL_MODE_ALTERNATE(7));
	palSetPadMode(BOARD_USART2_RTS_PORT, BOARD_USART2_RTS_PIN, PAL_MODE_ALTERNATE(7));
	palSetPadMode(BOARD_USART2_TX_PORT, BOARD_USART2_TX_PIN, PAL_MODE_ALTERNATE(7));
	palSetPadMode(BOARD_USART2_RX_PORT, BOARD_USART2_RX_PIN, PAL_MODE_ALTERNATE(7));
    serialConfig.speed = BOARD_USART2_BAUD;
    sdStart(&SD2, &serialConfig);
//    uartStart( &UARTD2, &uartConfig );
	#endif



	#if STM32_SPI_USE_SPI1
	palSetPadMode(BOARD_SPI1_CLK_PORT, BOARD_SPI1_CLK_PIN,
		PAL_STM32_MODE_ALTERNATE |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_FLOATING |
		PAL_STM32_ALTERNATE(5) );
	palSetPadMode(BOARD_SPI1_MISO_PORT, BOARD_SPI1_MISO_PIN,
		PAL_STM32_MODE_ALTERNATE |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_FLOATING |
		PAL_STM32_ALTERNATE(5) );
	palSetPadMode(BOARD_SPI1_MOSI_PORT, BOARD_SPI1_MOSI_PIN,
		PAL_STM32_MODE_ALTERNATE |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_FLOATING |
		PAL_STM32_ALTERNATE(5) );

	spiStart(&SPID1, &spi1Config);
	#endif

	#if STM32_SPI_USE_SPI2
	palSetPadMode(BOARD_SPI2_CLK_PORT, BOARD_SPI2_CLK_PIN,
		PAL_STM32_MODE_ALTERNATE |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_FLOATING |
		PAL_STM32_ALTERNATE(5) );
	palSetPadMode(BOARD_SPI2_MISO_PORT, BOARD_SPI2_MISO_PIN,
		PAL_STM32_MODE_ALTERNATE |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_PULLDOWN |
		PAL_STM32_ALTERNATE(5) );
	palSetPadMode(BOARD_SPI2_MOSI_PORT, BOARD_SPI2_MOSI_PIN,
		PAL_STM32_MODE_ALTERNATE |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_PULLDOWN |
		PAL_STM32_ALTERNATE(5) );

	palSetPadMode( BOARD_LS7366R_CS2_PORT, BOARD_LS7366R_CS2_PIN,
		PAL_STM32_MODE_OUTPUT |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_FLOATING );
	palSetPad( BOARD_LS7366R_CS2_PORT, BOARD_LS7366R_CS2_PIN );

	spiStart(&SPID2, &spi2Config);
	#endif

	#if STM32_PWM_USE_TIM2
	pwmStart(&BOARD_PWM_DEVICE1, &pwmConfig);
	palSetPadMode(BOARD_TIM2_CH1_PORT, BOARD_TIM2_CH1_PIN, PAL_MODE_ALTERNATE(1) );
	palSetPadMode(BOARD_TIM2_CH2_PORT, BOARD_TIM2_CH2_PIN, PAL_MODE_ALTERNATE(1) );
	palSetPadMode(BOARD_TIM2_CH3_PORT, BOARD_TIM2_CH3_PIN, PAL_MODE_ALTERNATE(1) );
	palSetPadMode(BOARD_TIM2_CH4_PORT, BOARD_TIM2_CH4_PIN, PAL_MODE_ALTERNATE(1) );
	#endif

	#if STM32_PWM_USE_TIM3
	pwmStart(&BOARD_PWM_DEVICE2, &pwmConfig);
	palSetPadMode(BOARD_TIM3_CH1_PORT, BOARD_TIM3_CH1_PIN, PAL_MODE_ALTERNATE(2) );
	palSetPadMode(BOARD_TIM3_CH2_PORT, BOARD_TIM3_CH2_PIN, PAL_MODE_ALTERNATE(2) );
	palSetPadMode(BOARD_TIM3_CH3_PORT, BOARD_TIM3_CH3_PIN, PAL_MODE_ALTERNATE(2) );
	palSetPadMode(BOARD_TIM3_CH4_PORT, BOARD_TIM3_CH4_PIN, PAL_MODE_ALTERNATE(2) );
	#endif

	palSetPadMode(BOARD_PWM_ENABLE_PORT, BOARD_PWM_ENABLE_PIN,
		PAL_STM32_MODE_OUTPUT |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_FLOATING );
	palClearPad(BOARD_PWM_ENABLE_PORT, BOARD_PWM_ENABLE_PIN);



	// ADIS16488 device init
	palSetPadMode( BOARD_ADIS16488_CS_PORT, BOARD_ADIS16488_CS_PIN,
		PAL_STM32_MODE_OUTPUT |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_FLOATING );
	palSetPad( BOARD_ADIS16488_CS_PORT, BOARD_ADIS16488_CS_PIN );
	palSetPadMode(BOARD_ADIS16488_RSTI_PORT, BOARD_ADIS16488_RSTI_PIN,
		PAL_STM32_MODE_OUTPUT |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_FLOATING );
	palSetPad(BOARD_ADIS16488_RSTI_PORT, BOARD_ADIS16488_RSTI_PIN);
	
	// LS7366R ESS inint
	palSetPadMode(BOARD_LS7366R_ESS_PORT, BOARD_LS7366R_ESS1_PIN,
		PAL_STM32_MODE_OUTPUT |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_FLOATING );
	palSetPad(BOARD_LS7366R_ESS_PORT, BOARD_LS7366R_ESS1_PIN);
	
	palSetPadMode(BOARD_LS7366R_ESS_PORT, BOARD_LS7366R_ESS2_PIN,
		PAL_STM32_MODE_OUTPUT |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_FLOATING );
	palSetPad(BOARD_LS7366R_ESS_PORT, BOARD_LS7366R_ESS2_PIN);
	
	palSetPadMode(BOARD_LS7366R_ESS_PORT, BOARD_LS7366R_ESS3_PIN,
		PAL_STM32_MODE_OUTPUT |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_FLOATING );
	palSetPad(BOARD_LS7366R_ESS_PORT, BOARD_LS7366R_ESS3_PIN);
	
	palSetPadMode(BOARD_LS7366R_ESS_PORT, BOARD_LS7366R_ESS4_PIN,
		PAL_STM32_MODE_OUTPUT |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_FLOATING );
	palSetPad(BOARD_LS7366R_ESS_PORT, BOARD_LS7366R_ESS4_PIN);
	
	palSetPadMode(BOARD_LS7366R_ESS_PORT, BOARD_LS7366R_ESS5_PIN,
		PAL_STM32_MODE_OUTPUT |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_FLOATING );
	palSetPad(BOARD_LS7366R_ESS_PORT, BOARD_LS7366R_ESS5_PIN);
	
	palSetPadMode(BOARD_LS7366R_ESS_PORT, BOARD_LS7366R_ESS6_PIN,
		PAL_STM32_MODE_OUTPUT |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_FLOATING );
	palSetPad(BOARD_LS7366R_ESS_PORT, BOARD_LS7366R_ESS6_PIN);
	
	palSetPadMode(BOARD_LS7366R_ESS_PORT, BOARD_LS7366R_ESS7_PIN,
		PAL_STM32_MODE_OUTPUT |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_FLOATING );
	palSetPad(BOARD_LS7366R_ESS_PORT, BOARD_LS7366R_ESS7_PIN);
	
	palSetPadMode(BOARD_LS7366R_ESS_PORT, BOARD_LS7366R_ESS8_PIN,
		PAL_STM32_MODE_OUTPUT |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_FLOATING );
	palSetPad(BOARD_LS7366R_ESS_PORT, BOARD_LS7366R_ESS8_PIN);
	
	palSetPadMode(BOARD_LS7366R_ESS_PORT, BOARD_LS7366R_ESS9_PIN,
		PAL_STM32_MODE_OUTPUT |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_FLOATING );
	palSetPad(BOARD_LS7366R_ESS_PORT, BOARD_LS7366R_ESS9_PIN);

	#if HAL_USE_SDC
	palSetPadMode(BOARD_SDIO_D0_PORT, BOARD_SDIO_D0_PIN,
		PAL_STM32_MODE_ALTERNATE |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_PULLUP |
		PAL_STM32_ALTERNATE(12) );
	palSetPadMode(BOARD_SDIO_D1_PORT, BOARD_SDIO_D1_PIN,
		PAL_STM32_MODE_ALTERNATE |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_PULLUP |
		PAL_STM32_ALTERNATE(12) );
	palSetPadMode(BOARD_SDIO_D2_PORT, BOARD_SDIO_D2_PIN,
		PAL_STM32_MODE_ALTERNATE |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_PULLUP |
		PAL_STM32_ALTERNATE(12) );
	palSetPadMode(BOARD_SDIO_D3_PORT, BOARD_SDIO_D3_PIN,
		PAL_STM32_MODE_ALTERNATE |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_PULLUP |
		PAL_STM32_ALTERNATE(12) );
	palSetPadMode(BOARD_SDIO_CMD_PORT, BOARD_SDIO_CMD_PIN,
		PAL_STM32_MODE_ALTERNATE |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_PULLUP |
		PAL_STM32_ALTERNATE(12) );
	palSetPadMode(BOARD_SDIO_CLK_PORT, BOARD_SDIO_CLK_PIN,
		PAL_STM32_MODE_ALTERNATE |
		PAL_STM32_OTYPE_PUSHPULL |
		PAL_STM32_OSPEED_HIGHEST |
		PAL_STM32_PUDR_PULLUP |
		PAL_STM32_ALTERNATE(12) );

	sdcStart(&SDCD1, NULL);
	#endif

    palSetPadMode(GPIOC, 15, PAL_MODE_OUTPUT_PUSHPULL);         // blue
    palClearPad(GPIOC, 15);
    palSetPadMode(GPIOC, 13, PAL_MODE_OUTPUT_PUSHPULL);         // red
    palClearPad(GPIOC, 13);
    palSetPadMode(GPIOC, 0, PAL_MODE_OUTPUT_PUSHPULL);          // orange
    palClearPad(GPIOC, 0);
    palSetPadMode(GPIOC, 14, PAL_MODE_OUTPUT_PUSHPULL);         // external?
    palClearPad(GPIOC, 14);
}


/**
 * @brief   Disable all enabled interfaces
 */
void boardStop(void) {
//    sduStop(&SDU1);

	// peripheral inint
    #if STM32_SERIAL_USE_USART1
	sdStop(&SD1);
	#endif

    #if STM32_UART_USE_USART2
    uartStop( &UARTD2 );
	#endif

	#if STM32_SPI_USE_SPI1
	spiStop(&SPID1);
	#endif

	#if STM32_SPI_USE_SPI2
	spiStop(&SPID2);
	#endif

	#if STM32_PWM_USE_TIM2
	pwmStop(&BOARD_PWM_DEVICE1);
	#endif

	#if STM32_PWM_USE_TIM3
	pwmStop(&BOARD_PWM_DEVICE2);
	#endif

	#if HAL_USE_SDC
	sdcStop(&SDCD1);
	#endif
}
