
set(STM32_CHIP STM32F415RG)
ADD_DEFINITIONS(-DCORTEX_USE_FPU=TRUE)

set(BOARD_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/board/${BOARDNAME}/board.c)
set(BOARD_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/board/${BOARDNAME})